# Service

apiVersion: v1
kind: Service
metadata:
  name: kubernates-app-config
spec:
  selector:
    app: kubernates-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernates-app-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernates-app
      tier: backend
  template:
    metadata:
      labels:
        app: kubernates-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: leonlogli/kubernates-app
