apiVersion: v1
kind: Service
metadata:
  name: kubernates-app-config
spec:
  selector:
    app: kubernates-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
